# Generated by Django 4.0 on 2022-03-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastroblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='id_article',
        ),
    ]
