# Generated by Django 2.2.12 on 2022-03-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastroblog', '0002_auto_20220329_1039'),
        ('gastroblog', '0002_auto_20220329_1045'),
    ]

    operations = [
    ]
