# Generated by Django 4.0 on 2022-03-29 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gastroblog', '0002_remove_comments_comment_remove_comments_id_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='comments',
            name='id_article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gastroblog.article'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
