# Generated by Django 4.0 on 2022-03-30 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastroblog', '0003_comments_comment_comments_id_article_comments_user_and_more'),
        ('gastroblog', '0003_merge_20220329_1102'),
    ]

    operations = [
    ]
