# Generated by Django 4.0 on 2022-03-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastrobar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='type',
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.CharField(max_length=12),
        ),
    ]
