# Generated by Django 2.2.3 on 2022-03-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastrobar', '0002_auto_20220329_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.IntegerField(),
        ),
    ]
