# Generated by Django 4.0 on 2022-03-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastrobar', '0002_remove_dish_type_alter_dish_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='dish',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mail',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.IntegerField(default=None, max_length=12),
        ),
    ]
