# Generated by Django 4.0 on 2022-03-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastrobar', '0003_dish_description_dish_name_dish_price_dish_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
