# Generated by Django 4.0 on 2022-03-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastrobar', '0004_alter_dish_photo'),
        ('gastrobar', '0004_merge_20220329_1102'),
    ]

    operations = [
    ]
